FORMAT: 1A

HOST: http://localhost:3000/api/v1

# Serialized

Serialized is an API for serving and storing serial stories and parts that make them up

# Group Users

User Resources

## User Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)


### Create new user [POST]

Users may register new accounts

+ Request (application/json)
  + Schema
    {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "first-name": {
          "type": "string"
        },
        "last-name": {
          "type": "string"
        },
        "birthdate": {
          "type": "date"
        },
      }
    }
+ Response 200 (application/json)
  {
    "status": 200
  }

+ Response 400 (application/json)

### Delete a User [DELETE]

+ Response 200

### Update a User [PUT]

# Group Auth

User Authentication

### Attempt User athentication
