FORMAT: 1A

HOST: http://localhost:3000/api/v1

# Serialized

Serialized is an API for serving and storing serial stories and parts that make them up

# Group Users

User Resources

## User Collection [/users]

### List All Users [GET]
+ Response 200 (application/json)
  + Schema
    {
      "type": "object",
      "properties": {
        "userData": {
          "type": "array"
          "items": [{
            "_id": "string"
          }]
        }
      }
    }
